# Generated by Django 4.1.3 on 2024-04-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("add_vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="document_renewal_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="libre_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
