# Generated by Django 4.1.3 on 2024-04-09 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("add_vehicle", "0002_alter_vehicle_document_renewal_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="edvla_renewal_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
